### ISSUE TITLE
Error during provision 

### ISSUE THREAD

**Issue by jenkoian** [javorszky/chassis-openssl#14]
Whenever I provision a fresh chassis install with this extension included, I get the following error. Any ideas?

`Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::openssl-nginx for site.local (file: /vagrant/puppet/manifests/chassis_openssl.pp, line: 15, column: 1) on node site.local`

**Comment by taulal** [comment]
Hey @jenkoian. Had the same issue. Found Chasis have their own fork: https://github.com/Chassis/chassis_openssl

**Comment by jenkoian** [comment]
Thanks @taulal I did work this out soon after, but forgot to close this. Will do so now, thanks for the info though 👍
