### ISSUE TITLE
Does this work for non-standard hosts? 

### ISSUE THREAD

**Issue by ericnicolaas** [javorszky/chassis-openssl#4]
I am attempting to set this up with a different host -- wpcharitable.local. When I boot up for the first time, there is an error:

```
==> default: Error: /Stage[main]/Main/File[/vagrant/vagrant.local.cert]: Could not evaluate: Could not retrieve information from environment production source(s) file:/etc/ssl/certs/vagrant.local.crt
==> default: Notice: /Stage[main]/Main/Openssl::Certificate::X509[vagrant.local]/Ssl_pkey[/etc/ssl/certs/vagrant.local.key]/ensure: created
==> default: Notice: /Stage[main]/Main/Openssl::Certificate::X509[vagrant.local]/File[/etc/ssl/certs/vagrant.local.key]/mode: mode changed '0644' to '0600'
==> default: Notice: /Stage[main]/Mysql::Server/Package[mysql-server]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Main/Package[git-core]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Main/Openssl::Certificate::X509[vagrant.local]/File[/etc/ssl/certs/vagrant.local.cnf]/ensure: created
==> default: Notice: /Stage[main]/Main/Openssl::Certificate::X509[vagrant.local]/X509_request[/etc/ssl/certs/vagrant.local.csr]/ensure: created
==> default: Notice: /Stage[main]/Main/Openssl::Certificate::X509[vagrant.local]/X509_cert[/etc/ssl/certs/vagrant.local.crt]/ensure: created
```

I tried changing `vagrant.local` to `wpcharitable.local` in the extension's `chassis.pp`, followed by `vagrant reload --provision`, but still no luck. 

Opening the site in Chrome results in an `This site can’t be reached. wpcharitable.local refused to connect.` message. 

Cheers, 
Eric

**Comment by ericnicolaas** [comment]
I reverted to `vagrant.local` for the host and that worked. However, I note that I am seeing the same errors as above, so apparently those are not related to `wpcharitable.local` not working.

**Comment by javorszky** [comment]
Hi @ericnicolaas!

Thanks for using this module. I think it _should_ work, but will test it out soon, please bear with me for a while, I'll get back to you.

**Comment by javorszky** [comment]
Hi @ericnicolaas,

I reproduced the problem. It was trying to copy the cert file before the cert file existed, and I've also set it so the file is named the same as the host. I tested it locally with `foo.local`, and it worked.

Let me know if you have any other problems with it.
