### ISSUE TITLE
Documentation: Modification of wp-config.php

### ISSUE THREAD

**Issue by dan-westall** [javorszky/chassis-openssl#6]
Currently the documentation states you should change `wp-config.php` on step 2.

This should reference the changing of `local-config.php` instead of `wp-config.php`, but currently `local-config.php` is not documented in chassis, see https://github.com/Chassis/Chassis/issues/196. Once 196 is completed will submit pr for docs

**Comment by javorszky** [comment]
Awesome, thank you. Has this been done? :)

**Comment by lgedeon** [comment]
I created a PR to fix this: https://github.com/javorszky/chassis-openssl/pull/13
