### ISSUE TITLE
Automatically add SSL certificate on macOS

### ISSUE THREAD

**Issue by morganestes** [javorszky/chassis-openssl#7]
On macOS, you can add the generated cert to the keychain via cli, but it requires sudo to run so that may be a deal breaker in the script, but thought I'd share it in case you or anyone else has an idea how to implement it.

```sh
sudo security add-trusted-cert -d -r trustRoot -p ssl -k /Library/Keychains/System.keychain /path/to/vagrant.local.cert
```

**Comment by shadyvb** [comment]
I don't think we have a way to execute commands on the host machine, the extension is purely working within the virtual environment.

Thanks for the tip though :)

**Comment by shadyvb** [comment]
Seems like we can define a command though to trust the certificate, something like what [SequelPro extension is doing](https://github.com/Chassis/SequelPro/blob/master/.vagrantplugins). Also possibly having it run after `vagrant up` using Vagrant triggers plugin as what [VVV is doing](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L453).

**Comment by javorszky** [comment]
Archiving the repository. Apparently Chassis has their own fork / maintained functionality of adding SSL certs to it per #14: https://github.com/Chassis/chassis_openssl

I am no longer maintaining this repository.
