### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID error in Chrome

### ISSUE THREAD

**Issue by ericnicolaas** [javorszky/chassis-openssl#8]
As of Chrome 58 the certificate is flagging a warning in Chrome. 

![screenshot 2017-05-10 10 49 54](https://cloud.githubusercontent.com/assets/676582/25879058/6a9e130c-356e-11e7-8a0d-d61d301e61b8.png)

Issue is referenced here: 

https://textslashplain.com/2017/03/10/chrome-deprecates-subject-cn-matching/

Linked to from that article is this on StackOverflow comment that seems pretty thorough in terms of how to set the subjectAltName: http://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl/27931596#27931596

**Comment by ericnicolaas** [comment]
I tried to fix this and regenerate a new security certificate with a small tweak to the extension's `chassis.pp`: 

```
openssl::certificate::x509 { $fqdn:
  country      => 'CH',
  organization => 'Example.com',
  commonname   => $fqdn,
  altnames     => [
    'one.example.com'
  ]
} ->
file { "/vagrant/${fqdn}.cert":
	ensure => present,
	source => "/etc/ssl/certs/${fqdn}.crt",
	mode => '0644',
}

include ::openssl-nginx
```

No luck, though from https://github.com/camptocamp/puppet-openssl/blob/master/manifests/certificate/x509.pp this does seem to be the way it should be set. But I'm way out of my depth here in terms of Puppet & certificates!

**Comment by ericnicolaas** [comment]
See reply on https://github.com/camptocamp/puppet-openssl/issues/44 — apparently setting `altnames` adds it to the request, but not the certificate.

**Comment by ericnicolaas** [comment]
OK, so I've found a workable solution but it requires editing the cert.cnf.erb provided in the openssl package. 

**chassis.pp**:

```
openssl::certificate::x509 { $fqdn:
  country      => 'CH',
  organization => 'Example.com',
  commonname   => $fqdn,
  altnames     => [ $fqdn ],
} ->
file { "/vagrant/${fqdn}.cert":
	ensure => present,
	source => "/etc/ssl/certs/${fqdn}.crt",
	mode => '0644',
}

include ::openssl-nginx
```

**modules/openssl/templates/cert.cnf.erb**
```
# file managed by puppet
#
# SSLeay example configuration file.
#

# This definition stops the following lines choking if HOME isn't
# defined.
HOME                    = .
RANDFILE                = $ENV::HOME/.rnd

[ req ]
default_bits            = 2048
default_md              = sha256
default_keyfile         = privkey.pem
distinguished_name      = req_distinguished_name
prompt                  = no
<% if @altnames and not @altnames.empty? -%>
req_extensions          = req_ext
x509_extensions         = req_ext
<% end -%>

[ req_distinguished_name ]
countryName                     = <%= @country %>
<% unless @state.nil? -%>
stateOrProvinceName             = <%= @state %>
<% end -%>
<% unless @locality.nil? -%>
localityName                    = <%= @locality %>
<% end -%>
organizationName                = <%= @organization %>
<% unless @unit.nil? -%>
organizationalUnitName          = <%= @unit %>
<% end -%>
commonName                      = <%= @commonname %>
<% unless @email.nil? -%>
emailAddress                    = <%= @email %>
<% end -%>

<% unless @altnames.empty? -%>
[ req_ext ]
subjectAltName = "<%= @altnames.collect! {|i| "DNS: #{i}" }.join(', ') -%>"
<% end %>
```

I have added a PR for the change to chassis.pp, but cert.cnf.erb is in the openssl module and so would need to be changed in their repo.

**Comment by javorszky** [comment]
Hiya! I'll review the PR in a sec. That's generally the case with local self signed certificates, Valet certs also have this problem. Thanks for taking the time to hunt it down though. :)

**Comment by ericnicolaas** [comment]
No worries, happy to help out :) Wasn't an issue until the Chrome upgrade, but satisfying to have been able to figure out a solution.
